In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [ ]:
from kret_notebook import *
from kret_polars._core.polars_nb_imports import *

from nba_timeout_impact.nb_imports import *

Loaded environment variables from /home/Akseldkw/coding/nba/NBA-Timeout-Impact/.env
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.0911 seconds

# Load Data

In [3]:
ds = CDNNBADatasetPL.load_from_parquet()
ds.head(3)

Validating cdnnba data (Polars)...
  Warning: game_seconds_elapsed has minor reversals in 91 games (instant replay / memo events — not a pipeline bug).
  Passed (4,168,786 rows, 74 cols, 1 warnings).

shape: (3, 74)
┌────────────┬──────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ game_date  ┆ gameId   ┆ orderNumbe ┆ actionTyp ┆ … ┆ y_court ┆ possessio ┆ possessio ┆ possessio │
│ ---        ┆ ---      ┆ r          ┆ e         ┆   ┆ ---     ┆ n_id      ┆ n_points  ┆ n_outcome │
│ datetime[m ┆ i64      ┆ ---        ┆ ---       ┆   ┆ i32     ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆ i64        ┆ cat       ┆   ┆         ┆ i64       ┆ i64       ┆ str       │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2020-12-23 ┆ 22000001 ┆ 20000      ┆ period    ┆ … ┆ null    ┆ null      ┆ null      ┆ null      │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2020-12-23 ┆ 22000001 ┆ 40000      ┆ jumpball  ┆ … ┆ null    ┆ 1         ┆ 0         ┆ turnover_ │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆ dead      │
│ 2020-12-23 ┆ 22000001 ┆ 70000      ┆ turnover  ┆ … ┆ null    ┆ 1         ┆ 0         ┆ turnover_ │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆ dead      │
└────────────┴──────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

# Memo Dataset

In [4]:
memo = CDNNBAMemoDFPL({"data": ds})
memo.head(3)

shape: (3, 74)
┌────────────┬──────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ game_date  ┆ gameId   ┆ orderNumbe ┆ actionTyp ┆ … ┆ y_court ┆ possessio ┆ possessio ┆ possessio │
│ ---        ┆ ---      ┆ r          ┆ e         ┆   ┆ ---     ┆ n_id      ┆ n_points  ┆ n_outcome │
│ datetime[m ┆ i64      ┆ ---        ┆ ---       ┆   ┆ i32     ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆ i64        ┆ cat       ┆   ┆         ┆ i64       ┆ i64       ┆ str       │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2020-12-23 ┆ 22000001 ┆ 20000      ┆ period    ┆ … ┆ null    ┆ null      ┆ null      ┆ null      │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2020-12-23 ┆ 22000001 ┆ 40000      ┆ jumpball  ┆ … ┆ null    ┆ 1         ┆ 0         ┆ turnover_ │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆ dead      │
│ 2020-12-23 ┆ 22000001 ┆ 70000      ┆ turnover  ┆ … ┆ null    ┆ 1         ┆ 0         ┆ turnover_ │
│ 00:00:00   ┆          ┆            ┆           ┆   ┆         ┆           ┆           ┆ dead      │
└────────────┴──────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [6]:
memo.to_polars_display().head(5)

shape: (5, 76)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬─────┬────────────┐
│ game_date  ┆ gameId   ┆ orderNumbe ┆ actionType ┆ … ┆ possession ┆ possession ┆ SEP ┆ f_clock_re │
│ ---        ┆ ---      ┆ r          ┆ ---        ┆   ┆ _points    ┆ _outcome   ┆ --- ┆ versal     │
│ datetime[m ┆ i64      ┆ ---        ┆ cat        ┆   ┆ ---        ┆ ---        ┆ str ┆ ---        │
│ s]         ┆          ┆ i64        ┆            ┆   ┆ i64        ┆ str        ┆     ┆ bool       │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═════╪════════════╡
│ 2020-12-23 ┆ 22000001 ┆ 20000      ┆ period     ┆ … ┆ null       ┆ null       ┆ ... ┆ false      │
│ 00:00:00   ┆          ┆            ┆            ┆   ┆            ┆            ┆     ┆            │
│ 2020-12-23 ┆ 22000001 ┆ 40000      ┆ jumpball   ┆ … ┆ 0          ┆ turnover_d ┆ ... ┆ false      │
│ 00:00:00   ┆          ┆            ┆            ┆   ┆            ┆ ead        ┆     ┆            │
│ 2020-12-23 ┆ 22000001 ┆ 70000      ┆ turnover   ┆ … ┆ 0          ┆ turnover_d ┆ ... ┆ false      │
│ 00:00:00   ┆          ┆            ┆            ┆   ┆            ┆ ead        ┆     ┆            │
│ 2020-12-23 ┆ 22000001 ┆ 80000      ┆ foul       ┆ … ┆ 2          ┆ ft_2_of_2  ┆ ... ┆ false      │
│ 00:00:00   ┆          ┆            ┆            ┆   ┆            ┆            ┆     ┆            │
│ 2020-12-23 ┆ 22000001 ┆ 100000     ┆ freethrow  ┆ … ┆ 2          ┆ ft_2_of_2  ┆ ... ┆ false      │
│ 00:00:00   ┆          ┆            ┆            ┆   ┆            ┆            ┆     ┆            │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴─────┴────────────┘

# Sandbox