In [28]:
%reload_ext autoreload
%autoreload 2

# Imports

In [29]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

In [ ]:
from nba_timeout_impact.data_pipes.load_data_utils import NBADataLoader
from nba_timeout_impact.data_pipes.clean_pipeline import NBAStatsV3CleanPipeline
from nba_timeout_impact.constants import NBAConstants
from nba_timeout_impact.nba_dataset import NBADataset, NBAMemoDF, NBADatasetInput_TypedDict
from nba_timeout_impact.nba_plotting_utils import NBAPlottingUtils

# Load Data

In [31]:
ret = available_seasons(data_type="nbastats")

In [32]:
ret

[1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

In [41]:
nba_stats = load_seasons(data_type="nbastats", playoffs=True)

In [42]:
UKS_NP_PD.dtt([nba_stats], show_dims=True)

In [43]:
nba_statsv3 = load_seasons(data_type="nbastatsv3", playoffs=True)

In [44]:
UKS_NP_PD.dtt([nba_statsv3], show_dims=True)

In [59]:
nba_statsv3.actionType.value_counts()

actionType
Rebound                                     43085
Missed Shot                                 39050
Made Shot                                   33160
Substitution                                20017
Free Throw                                  18679
Foul                                        17509
Turnover                                    10955
Timeout                                      4745
period                                       3410
Instant Replay                               1007
Jump Ball                                     784
Violation                                     609
Ejection                                       27
Instant Replay                                 21
Foul                                           17
Turnover                                        5
Name: count, dtype: int64

In [49]:
cdnnba = load_seasons(data_type="cdnnba", playoffs=True)

Loading data_type='cdnnba', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

In [50]:
UKS_NP_PD.dtt([cdnnba], show_dims=True)

In [53]:
pbpstats = load_seasons(data_type="pbpstats", playoffs=True)

Loading data_type='pbpstats', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

In [54]:
UKS_NP_PD.dtt([pbpstats], show_dims=True)

In [55]:
shotdetail = load_seasons(data_type="shotdetail", playoffs=True)

Loading data_type='shotdetail', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

In [56]:
UKS_NP_PD.dtt([shotdetail], show_dims=True)

In [57]:
matchups = load_seasons(data_type="matchups", playoffs=True)

Loading data_type='matchups', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

In [58]:
UKS_NP_PD.dtt([matchups], show_dims=True)

In [51]:
data_nba = load_seasons(data_type="datanba", playoffs=True)

Loading data_type='datanba', seasons=[2020, 2021, 2022, 2023, 2024], playoffs=True...

/Users/Akseldkw/coding/Columbia/NBA-Timeout-Impact/nba_timeout_impact/data_utils.py:106: DtypeWarning: Columns (0: wallclk) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(f)

In [52]:
UKS_NP_PD.dtt([data_nba], show_dims=True)

# Implementation

# Sandbox