In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [2]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

Loaded environment variables from /Users/Akseldkw/coding/Columbia/NBA-Timeout-Impact/.env
[kret_lgbm._core.lgbm_nb_imports] Imported kret_lgbm._core.lgbm_nb_imports in 2.3787 seconds
[kret_lightning._core.lightning_nb_imports] Imported kret_lightning._core.lightning_nb_imports in 4.3296 seconds
[kret_matplotlib._core.mpl_nb_imports] Imported kret_matplotlib._core.mpl_nb_imports in 0.3051 seconds
[kret_np_pd._core.np_pd_nb_imports] Imported kret_np_pd._core.np_pd_nb_imports in 0.0006 seconds
[kret_optuna._core.optuna_nb_imports] Imported kret_optuna._core.optuna_nb_imports in 0.0007 seconds
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.1099 seconds
[kret_rosetta._core.rosetta_nb_imports] Imported kret_rosetta._core.rosetta_nb_imports in 0.0000 seconds
[kret_sklearn._core.sklearn_nb_imports] Imported kret_sklearn._core.sklearn_nb_imports in 0.1871 seconds
[kret_torch_utils._core.torch_nb_imports] Imported kret_torch_utils._core.torch_nb_imports in 0.4316 seconds
[kret_tqdm._core.tqdm_nb_imports] Imported kret_tqdm._core.tqdm_nb_imports in 0.0003 seconds
[kret_type_hints._core.types_nb_imports] Imported kret_type_hints._core.types_nb_imports in 0.0013 seconds
[kret_utils._core.utils_nb_imports] Imported kret_utils._core.utils_nb_imports in 0.0012 seconds

In [31]:
from nba_timeout_impact.load_data_utils import *
from nba_timeout_impact.clean_pipeline import NBAStatsV3CleanPipeline

# Load Data

In [5]:
nba_statsv3 = load_seasons(data_type="nbastatsv3", playoffs=False, seasons=None)

Loading data_type='nbastatsv3', seasons=[1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], playoffs=False...

In [6]:
nba_statsv3_po = load_seasons(data_type="nbastatsv3", playoffs=True, seasons=None)

Loading data_type='nbastatsv3', seasons=[1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], playoffs=True...

# Implementation

In [7]:
UKS_CONSTANTS.DATA_DIR

PosixPath('/Users/Akseldkw/coding/data_kretsinger')

In [8]:
NBA_DATA_DIR = UKS_CONSTANTS.DATA_DIR / "NBA"
os.makedirs(NBA_DATA_DIR, exist_ok=True)

In [9]:
nba_statsv3.to_parquet(NBA_DATA_DIR / "nba_statsv3_regular_season.parquet")

In [10]:
nba_statsv3_po.to_parquet(NBA_DATA_DIR / "nba_statsv3_playoffs.parquet")

In [11]:
reload = pd.read_parquet(NBA_DATA_DIR / "nba_statsv3_regular_season.parquet")

# Sandbox

In [ ]:
df = nba_statsv3_po

In [18]:
UKS_NP_PD.dtt([df], show_dims=True)

In [23]:
out = df.nunique()

In [35]:
pipeline = NBAStatsV3CleanPipeline()
clean = pipeline.fit_transform_df(df)

In [36]:
UKS_NP_PD.dtt([clean])

,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,actionId,gameId,shotValue,seconds_remaining,seconds_elapsed
,int64,str,int64,int64,str,int64,str,str,int64,int64,int64,str,int64,float64,float64,int64,str,str,str,str,int64,int64,int64,float64,float64,float64
509678,33,PT08M33.00S,1,1610612756,PHX,255,Hill,G. Hill,0,0,0,NaN,0,0.000,0.000,0,h,Hill REBOUND (Off:0 Def:2),Rebound,Unknown,0,31,40900221,NaN,513.000,207.000
671755,193,PT06M31.00S,2,1610612757,POR,203115,Barton,W. Barton,0,0,0,NaN,0,0.000,0.000,0,h,Barton REBOUND (Off:0 Def:2),Rebound,Unknown,0,182,41300224,NaN,391.000,329.000
682833,128,PT00M04.60S,1,1610612748,MIA,2365,Andersen,C. Andersen,0,0,0,NaN,0,0.000,0.000,0,v,SUB: James FOR Andersen,Substitution,NaN,0,117,41300405,NaN,4.600,715.400
861861,188,PT11M28.00S,2,1610612762,UTA,1627777,Niang,G. Niang,-161,200,26,Made,1,33.000,31.000,64,h,Niang 26' 3PT Jump Shot (6 PTS) (Rubio 3 AST),Made Shot,Jump Shot,1,139,41800173,NaN,688.000,32.000
1112008,52,PT07M13.00S,1,1610612743,DEN,1629008,Porter Jr.,M. Porter Jr.,21,15,3,Missed,1,NaN,NaN,0,v,MISS Porter Jr. 3' Running Alley Oop Dunk Shot,Missed Shot,Running Alley Oop Dunk Shot,1,40,42400221,2.000,433.000,287.000